DBT_PRACTISE_SNOWFLAKE:
  target: dev
  outputs:
    dev:
      type: snowflake
      role: ACCOUNTADMIN
      warehouse: COMPUTE_WH
      database: DBT_LEARNING
      schema: RAW
      threads: 8
      
