version: 2

models:
  - name: stg_bookings
    columns:
      - name: booking_id
        tests:
          - not_null
          - unique

      - name: listing_id
        tests:
          - not_null
          - relationships:
              to: ref('stg_listings')
              field: listing_id

  - name: stg_listings
    columns:
      - name: listing_id
        tests:
          - not_null
          - unique

      - name: host_id
        tests:
          - not_null
          - relationships:
              to: ref('stg_hosts')
              field: host_id

  - name: stg_hosts
    columns:
      - name: host_id
        tests:
          - not_null
          - unique